// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"harnsplatform/internal/biz"
	"harnsplatform/internal/conf"
	"harnsplatform/internal/data"
	"harnsplatform/internal/server"
	"harnsplatform/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, log *log.Helper, logger log.Logger) (*kratos.App, func(), error) {

	dataData, cleanup, err := data.NewData(confData, log)
	if err != nil {
		return nil, nil, err
	}

	thingTypesRepo := data.NewThingTypesRepo(dataData, log)
	thingTypesUsecase := biz.NewThingTypesUsecase(thingTypesRepo, log)
	thingTypesService := service.NewThingTypesService(thingTypesUsecase, log)

	// grpcServer := server.NewGRPCServer(confServer, thingTypesService, logger)
	httpServer := server.NewHTTPServer(confServer, thingTypesService, log)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
