// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/modelmanager/v1/Brokers.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	"harnsplatform/internal/biz"
	"harnsplatform/internal/common"
	"harnsplatform/internal/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBrokersCreateBrokers = "/api.modelmanager.v1.Brokers/CreateBrokers"

type BrokersHTTPServer interface {
	CreateBrokers(context.Context, *Brokers) (*biz.Brokers, error)
	UpdateBrokersById(context.Context, *Brokers) (*biz.Brokers, error)
	DeleteBrokersById(context.Context, *biz.Meta) (*biz.Brokers, error)
	DeleteBrokers(context.Context, *BatchIds) (*BatchIds, error)
	GetBrokersById(context.Context, *biz.Meta) (*biz.Brokers, error)
	GetBrokers(context.Context, *biz.BrokersQuery) (*biz.PaginationResponse, error)
}

func RegisterBrokersHTTPServer(s *http.Server, srv BrokersHTTPServer) {
	r := s.Route("/")
	r.POST("/model-manager/v1/Brokers", CreateBrokers(srv))
	r.PUT("/model-manager/v1/Brokers/{id}", UpdateBrokersById(srv))
	r.GET("/model-manager/v1/Brokers/{id}", GetBrokersById(srv))
	r.DELETE("/model-manager/v1/Brokers/{id}", DeleteBrokersById(srv))
	r.POST("/model-manager/v1/deleteBrokersBatch", DeleteBrokers(srv))
	r.GET("/model-manager/v1/Brokers", GetBrokers(srv))
}

func CreateBrokers(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Brokers
		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBrokers(ctx, req.(*Brokers))
		})
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Brokers)
		return ctx.Result(200, reply)
	}
}

func UpdateBrokersById(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		version := ctx.Header().Get(common.ETAG)
		if len(version) == 0 {
			return errors.GenerateResourcePreconditionRequiredError(common.THINGS)
		}

		var in Brokers
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		in.Version = version

		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBrokersById(ctx, req.(*Brokers))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Brokers)
		return ctx.Result(200, reply)
	}
}

func GetBrokersById(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in biz.Meta
		if err := ctx.BindVars(&in); err != nil {
			return err
		}

		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBrokersById(ctx, req.(*biz.Meta))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Brokers)
		return ctx.Result(200, reply)
	}
}

func DeleteBrokersById(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in biz.Meta
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		version := ctx.Header().Get(common.ETAG)
		if len(version) == 0 {
			return errors.GenerateResourcePreconditionRequiredError(common.THINGS)
		}

		in.SetVersion(version)

		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBrokersById(ctx, req.(*biz.Meta))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Brokers)
		return ctx.Result(200, reply)
	}
}

func DeleteBrokers(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var bis BatchIds
		if err := ctx.Bind(&bis); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBrokers(ctx, req.(*BatchIds))
		})
		out, err := h(ctx, &bis)
		if err != nil {
			return err
		}
		reply := out.(*BatchIds)
		return ctx.Result(200, reply)
	}
}

func GetBrokers(srv BrokersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		ttq := biz.BrokersQuery{
			PaginationRequest: &biz.PaginationRequest{},
		}
		if err := ctx.BindQuery(&ttq); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBrokersCreateBrokers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBrokers(ctx, req.(*biz.BrokersQuery))
		})
		out, err := h(ctx, &ttq)
		if err != nil {
			return err
		}
		reply := out.(*biz.PaginationResponse)
		return ctx.Result(200, reply)
	}
}

type BrokersHTTPClient interface {
	CreateBrokers(ctx context.Context, req *Brokers, opts ...http.CallOption) (rsp *biz.Brokers, err error)
}

type BrokersHTTPClientImpl struct {
	cc *http.Client
}

func NewBrokersHTTPClient(client *http.Client) BrokersHTTPClient {
	return &BrokersHTTPClientImpl{client}
}

func (c *BrokersHTTPClientImpl) CreateBrokers(ctx context.Context, in *Brokers, opts ...http.CallOption) (*biz.Brokers, error) {
	var out biz.Brokers
	pattern := "/model-manager/v1/Brokers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBrokersCreateBrokers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
