// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/modelmanager/v1/thingTypes.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationThingTypesCreateThingTypes = "/api.modelmanager.v1.ThingTypes/CreateThingTypes"

type ThingTypesHTTPServer interface {
	CreateThingTypes(context.Context, *CreateThingTypesRequest) (*CreateThingTypesReply, error)
}

func RegisterThingTypesHTTPServer(s *http.Server, srv ThingTypesHTTPServer) {
	r := s.Route("/")
	r.POST("/model-manager/v1/thingTypes", _ThingTypes_CreateThingTypes0_HTTP_Handler(srv))
}

func _ThingTypes_CreateThingTypes0_HTTP_Handler(srv ThingTypesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateThingTypesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationThingTypesCreateThingTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateThingTypes(ctx, req.(*CreateThingTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateThingTypesReply)
		return ctx.Result(200, reply)
	}
}

type ThingTypesHTTPClient interface {
	CreateThingTypes(ctx context.Context, req *CreateThingTypesRequest, opts ...http.CallOption) (rsp *CreateThingTypesReply, err error)
}

type ThingTypesHTTPClientImpl struct {
	cc *http.Client
}

func NewThingTypesHTTPClient(client *http.Client) ThingTypesHTTPClient {
	return &ThingTypesHTTPClientImpl{client}
}

func (c *ThingTypesHTTPClientImpl) CreateThingTypes(ctx context.Context, in *CreateThingTypesRequest, opts ...http.CallOption) (*CreateThingTypesReply, error) {
	var out CreateThingTypesReply
	pattern := "/model-manager/v1/thingTypes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationThingTypesCreateThingTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
