// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/modelmanager/v1/Things.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	"harnsplatform/internal/biz"
	"harnsplatform/internal/common"
	"harnsplatform/internal/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationThingsCreateThings = "/api.modelmanager.v1.Things/CreateThings"

type ThingsHTTPServer interface {
	CreateThings(context.Context, *Things) (*biz.Things, error)
	UpdateThingsById(context.Context, *Things) (*biz.Things, error)
	DeleteThingsById(context.Context, *biz.Meta) (*biz.Things, error)
	DeleteThings(context.Context, *BatchIds) (*BatchIds, error)
	GetThingsById(context.Context, *biz.Meta) (*biz.Things, error)
	GetThings(context.Context, *biz.ThingsQuery) (*biz.PaginationResponse, error)
}

func RegisterThingsHTTPServer(s *http.Server, srv ThingsHTTPServer) {
	r := s.Route("/")
	r.POST("/model-manager/v1/things", CreateThings(srv))
	r.PUT("/model-manager/v1/things/{id}", UpdateThingsById(srv))
	r.GET("/model-manager/v1/things/{id}", GetThingsById(srv))
	r.DELETE("/model-manager/v1/things/{id}", DeleteThingsById(srv))
	r.POST("/model-manager/v1/deleteThingsBatch", DeleteThings(srv))
	r.GET("/model-manager/v1/things", GetThings(srv))
}

func CreateThings(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Things
		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateThings(ctx, req.(*Things))
		})
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Things)
		return ctx.Result(200, reply)
	}
}

func UpdateThingsById(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		version := ctx.Header().Get(common.ETAG)
		if len(version) == 0 {
			return errors.GenerateResourcePreconditionRequiredError(common.THINGS)
		}

		var in Things
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		in.Version = version

		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateThingsById(ctx, req.(*Things))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Things)
		return ctx.Result(200, reply)
	}
}

func GetThingsById(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in biz.Meta
		if err := ctx.BindVars(&in); err != nil {
			return err
		}

		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetThingsById(ctx, req.(*biz.Meta))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Things)
		return ctx.Result(200, reply)
	}
}

func DeleteThingsById(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in biz.Meta
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		version := ctx.Header().Get(common.ETAG)
		if len(version) == 0 {
			return errors.GenerateResourcePreconditionRequiredError(common.THINGS)
		}

		in.SetVersion(version)

		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteThingsById(ctx, req.(*biz.Meta))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*biz.Things)
		return ctx.Result(200, reply)
	}
}

func DeleteThings(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var bis BatchIds
		if err := ctx.Bind(&bis); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteThings(ctx, req.(*BatchIds))
		})
		out, err := h(ctx, &bis)
		if err != nil {
			return err
		}
		reply := out.(*BatchIds)
		return ctx.Result(200, reply)
	}
}

func GetThings(srv ThingsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		ttq := biz.ThingsQuery{
			PaginationRequest: &biz.PaginationRequest{},
		}
		if err := ctx.BindQuery(&ttq); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationThingsCreateThings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetThings(ctx, req.(*biz.ThingsQuery))
		})
		out, err := h(ctx, &ttq)
		if err != nil {
			return err
		}
		reply := out.(*biz.PaginationResponse)
		return ctx.Result(200, reply)
	}
}

type ThingsHTTPClient interface {
	CreateThings(ctx context.Context, req *Things, opts ...http.CallOption) (rsp *biz.Things, err error)
}

type ThingsHTTPClientImpl struct {
	cc *http.Client
}

func NewThingsHTTPClient(client *http.Client) ThingsHTTPClient {
	return &ThingsHTTPClientImpl{client}
}

func (c *ThingsHTTPClientImpl) CreateThings(ctx context.Context, in *Things, opts ...http.CallOption) (*biz.Things, error) {
	var out biz.Things
	pattern := "/model-manager/v1/Things"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationThingsCreateThings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
